// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: workouts/workouts.proto

package workout

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExerciseService_GetExercises_FullMethodName            = "/fitness_trainer.api.workout.ExerciseService/GetExercises"
	ExerciseService_CreateExercise_FullMethodName          = "/fitness_trainer.api.workout.ExerciseService/CreateExercise"
	ExerciseService_GetExerciseDetail_FullMethodName       = "/fitness_trainer.api.workout.ExerciseService/GetExerciseDetail"
	ExerciseService_GetExerciseAlternatives_FullMethodName = "/fitness_trainer.api.workout.ExerciseService/GetExerciseAlternatives"
	ExerciseService_GetExerciseHistory_FullMethodName      = "/fitness_trainer.api.workout.ExerciseService/GetExerciseHistory"
	ExerciseService_GetMuscleGroups_FullMethodName         = "/fitness_trainer.api.workout.ExerciseService/GetMuscleGroups"
)

// ExerciseServiceClient is the client API for ExerciseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExerciseServiceClient interface {
	// Метод для получения списка всех упражнений
	GetExercises(ctx context.Context, in *GetExercisesRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error)
	// Метод для создания нового упражнения
	CreateExercise(ctx context.Context, in *CreateExerciseRequest, opts ...grpc.CallOption) (*ExerciseResponse, error)
	// Метод для получения деталей об упражнении
	GetExerciseDetail(ctx context.Context, in *GetExerciseDetailRequest, opts ...grpc.CallOption) (*ExerciseResponse, error)
	// Метод для получения альтернативных упражнений по exercise_id
	GetExerciseAlternatives(ctx context.Context, in *GetExerciseAlternativesRequest, opts ...grpc.CallOption) (*GetExerciseAlternativesResponse, error)
	// Метод для получения истории выполнения упражнения
	GetExerciseHistory(ctx context.Context, in *GetExerciseHistoryRequest, opts ...grpc.CallOption) (*ExerciseHistoryResponse, error)
	// Метод для получения списка групп мышц
	GetMuscleGroups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMuscleGroupsResponse, error)
}

type exerciseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExerciseServiceClient(cc grpc.ClientConnInterface) ExerciseServiceClient {
	return &exerciseServiceClient{cc}
}

func (c *exerciseServiceClient) GetExercises(ctx context.Context, in *GetExercisesRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) CreateExercise(ctx context.Context, in *CreateExerciseRequest, opts ...grpc.CallOption) (*ExerciseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseResponse)
	err := c.cc.Invoke(ctx, ExerciseService_CreateExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetExerciseDetail(ctx context.Context, in *GetExerciseDetailRequest, opts ...grpc.CallOption) (*ExerciseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetExerciseDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetExerciseAlternatives(ctx context.Context, in *GetExerciseAlternativesRequest, opts ...grpc.CallOption) (*GetExerciseAlternativesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExerciseAlternativesResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetExerciseAlternatives_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetExerciseHistory(ctx context.Context, in *GetExerciseHistoryRequest, opts ...grpc.CallOption) (*ExerciseHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseHistoryResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetExerciseHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetMuscleGroups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMuscleGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMuscleGroupsResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetMuscleGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseServiceServer is the server API for ExerciseService service.
// All implementations must embed UnimplementedExerciseServiceServer
// for forward compatibility.
type ExerciseServiceServer interface {
	// Метод для получения списка всех упражнений
	GetExercises(context.Context, *GetExercisesRequest) (*GetExercisesResponse, error)
	// Метод для создания нового упражнения
	CreateExercise(context.Context, *CreateExerciseRequest) (*ExerciseResponse, error)
	// Метод для получения деталей об упражнении
	GetExerciseDetail(context.Context, *GetExerciseDetailRequest) (*ExerciseResponse, error)
	// Метод для получения альтернативных упражнений по exercise_id
	GetExerciseAlternatives(context.Context, *GetExerciseAlternativesRequest) (*GetExerciseAlternativesResponse, error)
	// Метод для получения истории выполнения упражнения
	GetExerciseHistory(context.Context, *GetExerciseHistoryRequest) (*ExerciseHistoryResponse, error)
	// Метод для получения списка групп мышц
	GetMuscleGroups(context.Context, *emptypb.Empty) (*GetMuscleGroupsResponse, error)
	mustEmbedUnimplementedExerciseServiceServer()
}

// UnimplementedExerciseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExerciseServiceServer struct{}

func (UnimplementedExerciseServiceServer) GetExercises(context.Context, *GetExercisesRequest) (*GetExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExercises not implemented")
}
func (UnimplementedExerciseServiceServer) CreateExercise(context.Context, *CreateExerciseRequest) (*ExerciseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExercise not implemented")
}
func (UnimplementedExerciseServiceServer) GetExerciseDetail(context.Context, *GetExerciseDetailRequest) (*ExerciseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseDetail not implemented")
}
func (UnimplementedExerciseServiceServer) GetExerciseAlternatives(context.Context, *GetExerciseAlternativesRequest) (*GetExerciseAlternativesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseAlternatives not implemented")
}
func (UnimplementedExerciseServiceServer) GetExerciseHistory(context.Context, *GetExerciseHistoryRequest) (*ExerciseHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseHistory not implemented")
}
func (UnimplementedExerciseServiceServer) GetMuscleGroups(context.Context, *emptypb.Empty) (*GetMuscleGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMuscleGroups not implemented")
}
func (UnimplementedExerciseServiceServer) mustEmbedUnimplementedExerciseServiceServer() {}
func (UnimplementedExerciseServiceServer) testEmbeddedByValue()                         {}

// UnsafeExerciseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExerciseServiceServer will
// result in compilation errors.
type UnsafeExerciseServiceServer interface {
	mustEmbedUnimplementedExerciseServiceServer()
}

func RegisterExerciseServiceServer(s grpc.ServiceRegistrar, srv ExerciseServiceServer) {
	// If the following call pancis, it indicates UnimplementedExerciseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExerciseService_ServiceDesc, srv)
}

func _ExerciseService_GetExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExercises(ctx, req.(*GetExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_CreateExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).CreateExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_CreateExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).CreateExercise(ctx, req.(*CreateExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetExerciseDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExerciseDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExerciseDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExerciseDetail(ctx, req.(*GetExerciseDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetExerciseAlternatives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseAlternativesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExerciseAlternatives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExerciseAlternatives_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExerciseAlternatives(ctx, req.(*GetExerciseAlternativesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetExerciseHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExerciseHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExerciseHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExerciseHistory(ctx, req.(*GetExerciseHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetMuscleGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetMuscleGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetMuscleGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetMuscleGroups(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExerciseService_ServiceDesc is the grpc.ServiceDesc for ExerciseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExerciseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitness_trainer.api.workout.ExerciseService",
	HandlerType: (*ExerciseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExercises",
			Handler:    _ExerciseService_GetExercises_Handler,
		},
		{
			MethodName: "CreateExercise",
			Handler:    _ExerciseService_CreateExercise_Handler,
		},
		{
			MethodName: "GetExerciseDetail",
			Handler:    _ExerciseService_GetExerciseDetail_Handler,
		},
		{
			MethodName: "GetExerciseAlternatives",
			Handler:    _ExerciseService_GetExerciseAlternatives_Handler,
		},
		{
			MethodName: "GetExerciseHistory",
			Handler:    _ExerciseService_GetExerciseHistory_Handler,
		},
		{
			MethodName: "GetMuscleGroups",
			Handler:    _ExerciseService_GetMuscleGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workouts/workouts.proto",
}

const (
	RoutineService_GetRoutines_FullMethodName                       = "/fitness_trainer.api.workout.RoutineService/GetRoutines"
	RoutineService_CreateRoutine_FullMethodName                     = "/fitness_trainer.api.workout.RoutineService/CreateRoutine"
	RoutineService_UpdateRoutine_FullMethodName                     = "/fitness_trainer.api.workout.RoutineService/UpdateRoutine"
	RoutineService_GetRoutineDetail_FullMethodName                  = "/fitness_trainer.api.workout.RoutineService/GetRoutineDetail"
	RoutineService_DeleteRoutine_FullMethodName                     = "/fitness_trainer.api.workout.RoutineService/DeleteRoutine"
	RoutineService_AddExerciseToRoutine_FullMethodName              = "/fitness_trainer.api.workout.RoutineService/AddExerciseToRoutine"
	RoutineService_GetExerciseInstanceDetails_FullMethodName        = "/fitness_trainer.api.workout.RoutineService/GetExerciseInstanceDetails"
	RoutineService_RemoveExerciseInstanceFromRoutine_FullMethodName = "/fitness_trainer.api.workout.RoutineService/RemoveExerciseInstanceFromRoutine"
	RoutineService_AddSetToExerciseInstance_FullMethodName          = "/fitness_trainer.api.workout.RoutineService/AddSetToExerciseInstance"
	RoutineService_UpdateSetInExerciseInstance_FullMethodName       = "/fitness_trainer.api.workout.RoutineService/UpdateSetInExerciseInstance"
	RoutineService_RemoveSetFromExerciseInstance_FullMethodName     = "/fitness_trainer.api.workout.RoutineService/RemoveSetFromExerciseInstance"
	RoutineService_SetExerciseOrder_FullMethodName                  = "/fitness_trainer.api.workout.RoutineService/SetExerciseOrder"
)

// RoutineServiceClient is the client API for RoutineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutineServiceClient interface {
	// Метод для получения списка доступных пользователю рутин
	GetRoutines(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoutineListResponse, error)
	// Создание новой рутины
	CreateRoutine(ctx context.Context, in *CreateRoutineRequest, opts ...grpc.CallOption) (*RoutineResponse, error)
	// Обновление рутины по ID
	UpdateRoutine(ctx context.Context, in *UpdateRoutineRequest, opts ...grpc.CallOption) (*RoutineResponse, error)
	// Получение информации о рутине по ID
	GetRoutineDetail(ctx context.Context, in *GetRoutineDetailRequest, opts ...grpc.CallOption) (*RoutineDetailResponse, error)
	// Удаление рутины по ID
	DeleteRoutine(ctx context.Context, in *DeleteRoutineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Добавление упражнения в рутину
	AddExerciseToRoutine(ctx context.Context, in *AddExerciseToRoutineRequest, opts ...grpc.CallOption) (*RoutineInstanceResponse, error)
	// Получить информацию об упражнении в рутине
	GetExerciseInstanceDetails(ctx context.Context, in *GetExerciseInstanceDetailsRequest, opts ...grpc.CallOption) (*GetExerciseInstanceDetailsResponse, error)
	// Удаление упражнения из рутины
	RemoveExerciseInstanceFromRoutine(ctx context.Context, in *RemoveExerciseInstanceFromRoutineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для добавления сета в упражнение
	AddSetToExerciseInstance(ctx context.Context, in *AddSetToExerciseInstanceRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Метод для обновления сета в упражнении
	UpdateSetInExerciseInstance(ctx context.Context, in *UpdateSetInExerciseInstanceRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Метод для удаления сета из упражнения
	RemoveSetFromExerciseInstance(ctx context.Context, in *RemoveSetFromExerciseInstanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для установки порядка упражнений в рутине
	SetExerciseOrder(ctx context.Context, in *SetExerciseOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type routineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutineServiceClient(cc grpc.ClientConnInterface) RoutineServiceClient {
	return &routineServiceClient{cc}
}

func (c *routineServiceClient) GetRoutines(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoutineListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutineListResponse)
	err := c.cc.Invoke(ctx, RoutineService_GetRoutines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) CreateRoutine(ctx context.Context, in *CreateRoutineRequest, opts ...grpc.CallOption) (*RoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutineResponse)
	err := c.cc.Invoke(ctx, RoutineService_CreateRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) UpdateRoutine(ctx context.Context, in *UpdateRoutineRequest, opts ...grpc.CallOption) (*RoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutineResponse)
	err := c.cc.Invoke(ctx, RoutineService_UpdateRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) GetRoutineDetail(ctx context.Context, in *GetRoutineDetailRequest, opts ...grpc.CallOption) (*RoutineDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutineDetailResponse)
	err := c.cc.Invoke(ctx, RoutineService_GetRoutineDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) DeleteRoutine(ctx context.Context, in *DeleteRoutineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoutineService_DeleteRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) AddExerciseToRoutine(ctx context.Context, in *AddExerciseToRoutineRequest, opts ...grpc.CallOption) (*RoutineInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutineInstanceResponse)
	err := c.cc.Invoke(ctx, RoutineService_AddExerciseToRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) GetExerciseInstanceDetails(ctx context.Context, in *GetExerciseInstanceDetailsRequest, opts ...grpc.CallOption) (*GetExerciseInstanceDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExerciseInstanceDetailsResponse)
	err := c.cc.Invoke(ctx, RoutineService_GetExerciseInstanceDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) RemoveExerciseInstanceFromRoutine(ctx context.Context, in *RemoveExerciseInstanceFromRoutineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoutineService_RemoveExerciseInstanceFromRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) AddSetToExerciseInstance(ctx context.Context, in *AddSetToExerciseInstanceRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, RoutineService_AddSetToExerciseInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) UpdateSetInExerciseInstance(ctx context.Context, in *UpdateSetInExerciseInstanceRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, RoutineService_UpdateSetInExerciseInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) RemoveSetFromExerciseInstance(ctx context.Context, in *RemoveSetFromExerciseInstanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoutineService_RemoveSetFromExerciseInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routineServiceClient) SetExerciseOrder(ctx context.Context, in *SetExerciseOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoutineService_SetExerciseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutineServiceServer is the server API for RoutineService service.
// All implementations must embed UnimplementedRoutineServiceServer
// for forward compatibility.
type RoutineServiceServer interface {
	// Метод для получения списка доступных пользователю рутин
	GetRoutines(context.Context, *emptypb.Empty) (*RoutineListResponse, error)
	// Создание новой рутины
	CreateRoutine(context.Context, *CreateRoutineRequest) (*RoutineResponse, error)
	// Обновление рутины по ID
	UpdateRoutine(context.Context, *UpdateRoutineRequest) (*RoutineResponse, error)
	// Получение информации о рутине по ID
	GetRoutineDetail(context.Context, *GetRoutineDetailRequest) (*RoutineDetailResponse, error)
	// Удаление рутины по ID
	DeleteRoutine(context.Context, *DeleteRoutineRequest) (*emptypb.Empty, error)
	// Добавление упражнения в рутину
	AddExerciseToRoutine(context.Context, *AddExerciseToRoutineRequest) (*RoutineInstanceResponse, error)
	// Получить информацию об упражнении в рутине
	GetExerciseInstanceDetails(context.Context, *GetExerciseInstanceDetailsRequest) (*GetExerciseInstanceDetailsResponse, error)
	// Удаление упражнения из рутины
	RemoveExerciseInstanceFromRoutine(context.Context, *RemoveExerciseInstanceFromRoutineRequest) (*emptypb.Empty, error)
	// Метод для добавления сета в упражнение
	AddSetToExerciseInstance(context.Context, *AddSetToExerciseInstanceRequest) (*SetResponse, error)
	// Метод для обновления сета в упражнении
	UpdateSetInExerciseInstance(context.Context, *UpdateSetInExerciseInstanceRequest) (*SetResponse, error)
	// Метод для удаления сета из упражнения
	RemoveSetFromExerciseInstance(context.Context, *RemoveSetFromExerciseInstanceRequest) (*emptypb.Empty, error)
	// Метод для установки порядка упражнений в рутине
	SetExerciseOrder(context.Context, *SetExerciseOrderRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRoutineServiceServer()
}

// UnimplementedRoutineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutineServiceServer struct{}

func (UnimplementedRoutineServiceServer) GetRoutines(context.Context, *emptypb.Empty) (*RoutineListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutines not implemented")
}
func (UnimplementedRoutineServiceServer) CreateRoutine(context.Context, *CreateRoutineRequest) (*RoutineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoutine not implemented")
}
func (UnimplementedRoutineServiceServer) UpdateRoutine(context.Context, *UpdateRoutineRequest) (*RoutineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoutine not implemented")
}
func (UnimplementedRoutineServiceServer) GetRoutineDetail(context.Context, *GetRoutineDetailRequest) (*RoutineDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutineDetail not implemented")
}
func (UnimplementedRoutineServiceServer) DeleteRoutine(context.Context, *DeleteRoutineRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoutine not implemented")
}
func (UnimplementedRoutineServiceServer) AddExerciseToRoutine(context.Context, *AddExerciseToRoutineRequest) (*RoutineInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExerciseToRoutine not implemented")
}
func (UnimplementedRoutineServiceServer) GetExerciseInstanceDetails(context.Context, *GetExerciseInstanceDetailsRequest) (*GetExerciseInstanceDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseInstanceDetails not implemented")
}
func (UnimplementedRoutineServiceServer) RemoveExerciseInstanceFromRoutine(context.Context, *RemoveExerciseInstanceFromRoutineRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExerciseInstanceFromRoutine not implemented")
}
func (UnimplementedRoutineServiceServer) AddSetToExerciseInstance(context.Context, *AddSetToExerciseInstanceRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSetToExerciseInstance not implemented")
}
func (UnimplementedRoutineServiceServer) UpdateSetInExerciseInstance(context.Context, *UpdateSetInExerciseInstanceRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSetInExerciseInstance not implemented")
}
func (UnimplementedRoutineServiceServer) RemoveSetFromExerciseInstance(context.Context, *RemoveSetFromExerciseInstanceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSetFromExerciseInstance not implemented")
}
func (UnimplementedRoutineServiceServer) SetExerciseOrder(context.Context, *SetExerciseOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetExerciseOrder not implemented")
}
func (UnimplementedRoutineServiceServer) mustEmbedUnimplementedRoutineServiceServer() {}
func (UnimplementedRoutineServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutineServiceServer will
// result in compilation errors.
type UnsafeRoutineServiceServer interface {
	mustEmbedUnimplementedRoutineServiceServer()
}

func RegisterRoutineServiceServer(s grpc.ServiceRegistrar, srv RoutineServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutineService_ServiceDesc, srv)
}

func _RoutineService_GetRoutines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).GetRoutines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_GetRoutines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).GetRoutines(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_CreateRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).CreateRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_CreateRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).CreateRoutine(ctx, req.(*CreateRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_UpdateRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).UpdateRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_UpdateRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).UpdateRoutine(ctx, req.(*UpdateRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_GetRoutineDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutineDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).GetRoutineDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_GetRoutineDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).GetRoutineDetail(ctx, req.(*GetRoutineDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_DeleteRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).DeleteRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_DeleteRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).DeleteRoutine(ctx, req.(*DeleteRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_AddExerciseToRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExerciseToRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).AddExerciseToRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_AddExerciseToRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).AddExerciseToRoutine(ctx, req.(*AddExerciseToRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_GetExerciseInstanceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseInstanceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).GetExerciseInstanceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_GetExerciseInstanceDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).GetExerciseInstanceDetails(ctx, req.(*GetExerciseInstanceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_RemoveExerciseInstanceFromRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveExerciseInstanceFromRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).RemoveExerciseInstanceFromRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_RemoveExerciseInstanceFromRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).RemoveExerciseInstanceFromRoutine(ctx, req.(*RemoveExerciseInstanceFromRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_AddSetToExerciseInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSetToExerciseInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).AddSetToExerciseInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_AddSetToExerciseInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).AddSetToExerciseInstance(ctx, req.(*AddSetToExerciseInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_UpdateSetInExerciseInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSetInExerciseInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).UpdateSetInExerciseInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_UpdateSetInExerciseInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).UpdateSetInExerciseInstance(ctx, req.(*UpdateSetInExerciseInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_RemoveSetFromExerciseInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSetFromExerciseInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).RemoveSetFromExerciseInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_RemoveSetFromExerciseInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).RemoveSetFromExerciseInstance(ctx, req.(*RemoveSetFromExerciseInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutineService_SetExerciseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExerciseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutineServiceServer).SetExerciseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutineService_SetExerciseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutineServiceServer).SetExerciseOrder(ctx, req.(*SetExerciseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutineService_ServiceDesc is the grpc.ServiceDesc for RoutineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitness_trainer.api.workout.RoutineService",
	HandlerType: (*RoutineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoutines",
			Handler:    _RoutineService_GetRoutines_Handler,
		},
		{
			MethodName: "CreateRoutine",
			Handler:    _RoutineService_CreateRoutine_Handler,
		},
		{
			MethodName: "UpdateRoutine",
			Handler:    _RoutineService_UpdateRoutine_Handler,
		},
		{
			MethodName: "GetRoutineDetail",
			Handler:    _RoutineService_GetRoutineDetail_Handler,
		},
		{
			MethodName: "DeleteRoutine",
			Handler:    _RoutineService_DeleteRoutine_Handler,
		},
		{
			MethodName: "AddExerciseToRoutine",
			Handler:    _RoutineService_AddExerciseToRoutine_Handler,
		},
		{
			MethodName: "GetExerciseInstanceDetails",
			Handler:    _RoutineService_GetExerciseInstanceDetails_Handler,
		},
		{
			MethodName: "RemoveExerciseInstanceFromRoutine",
			Handler:    _RoutineService_RemoveExerciseInstanceFromRoutine_Handler,
		},
		{
			MethodName: "AddSetToExerciseInstance",
			Handler:    _RoutineService_AddSetToExerciseInstance_Handler,
		},
		{
			MethodName: "UpdateSetInExerciseInstance",
			Handler:    _RoutineService_UpdateSetInExerciseInstance_Handler,
		},
		{
			MethodName: "RemoveSetFromExerciseInstance",
			Handler:    _RoutineService_RemoveSetFromExerciseInstance_Handler,
		},
		{
			MethodName: "SetExerciseOrder",
			Handler:    _RoutineService_SetExerciseOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workouts/workouts.proto",
}

const (
	WorkoutService_StartWorkout_FullMethodName                = "/fitness_trainer.api.workout.WorkoutService/StartWorkout"
	WorkoutService_GenerateWorkout_FullMethodName             = "/fitness_trainer.api.workout.WorkoutService/GenerateWorkout"
	WorkoutService_GetWorkout_FullMethodName                  = "/fitness_trainer.api.workout.WorkoutService/GetWorkout"
	WorkoutService_DeleteWorkout_FullMethodName               = "/fitness_trainer.api.workout.WorkoutService/DeleteWorkout"
	WorkoutService_GetActiveWorkouts_FullMethodName           = "/fitness_trainer.api.workout.WorkoutService/GetActiveWorkouts"
	WorkoutService_GetWorkouts_FullMethodName                 = "/fitness_trainer.api.workout.WorkoutService/GetWorkouts"
	WorkoutService_LogExercise_FullMethodName                 = "/fitness_trainer.api.workout.WorkoutService/LogExercise"
	WorkoutService_GetExerciseLogDetails_FullMethodName       = "/fitness_trainer.api.workout.WorkoutService/GetExerciseLogDetails"
	WorkoutService_DeleteExerciseLog_FullMethodName           = "/fitness_trainer.api.workout.WorkoutService/DeleteExerciseLog"
	WorkoutService_AddPowerRatingToExerciseLog_FullMethodName = "/fitness_trainer.api.workout.WorkoutService/AddPowerRatingToExerciseLog"
	WorkoutService_AddNotesToExerciseLog_FullMethodName       = "/fitness_trainer.api.workout.WorkoutService/AddNotesToExerciseLog"
	WorkoutService_LogSet_FullMethodName                      = "/fitness_trainer.api.workout.WorkoutService/LogSet"
	WorkoutService_UpdateSetLog_FullMethodName                = "/fitness_trainer.api.workout.WorkoutService/UpdateSetLog"
	WorkoutService_DeleteSetLog_FullMethodName                = "/fitness_trainer.api.workout.WorkoutService/DeleteSetLog"
	WorkoutService_CompleteWorkout_FullMethodName             = "/fitness_trainer.api.workout.WorkoutService/CompleteWorkout"
	WorkoutService_GetWorkoutReport_FullMethodName            = "/fitness_trainer.api.workout.WorkoutService/GetWorkoutReport"
	WorkoutService_RateWorkout_FullMethodName                 = "/fitness_trainer.api.workout.WorkoutService/RateWorkout"
	WorkoutService_AddCommentToWorkout_FullMethodName         = "/fitness_trainer.api.workout.WorkoutService/AddCommentToWorkout"
	WorkoutService_UpdateExerciseLogWeightUnit_FullMethodName = "/fitness_trainer.api.workout.WorkoutService/UpdateExerciseLogWeightUnit"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	// Метод для начала новой тренировки
	StartWorkout(ctx context.Context, in *StartWorkoutRequest, opts ...grpc.CallOption) (*WorkoutResponse, error)
	// Запустить (или перезапустить после ошибки) генерацию тренировки
	GenerateWorkout(ctx context.Context, in *GenerateWorkoutRequest, opts ...grpc.CallOption) (*GenerateWorkoutResponse, error)
	// Метод для получения состояния тренировки
	GetWorkout(ctx context.Context, in *GetWorkoutRequest, opts ...grpc.CallOption) (*GetWorkoutResponse, error)
	// Удалить тренировку
	DeleteWorkout(ctx context.Context, in *DeleteWorkoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для получения списка активных тренировок
	GetActiveWorkouts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkoutsListResponse, error)
	// Метод для получения списка всех тренировок
	GetWorkouts(ctx context.Context, in *GetWorkoutsRequest, opts ...grpc.CallOption) (*GetWorkoutsResponse, error)
	// Метод для создания записи о выполнении упражнения
	LogExercise(ctx context.Context, in *LogExerciseRequest, opts ...grpc.CallOption) (*ExerciseLog, error)
	// Метод для получения записи о выполнении упражнения
	GetExerciseLogDetails(ctx context.Context, in *GetExerciseLogDetailRequest, opts ...grpc.CallOption) (*ExerciseLogResponse, error)
	// Удалить запись о выполнении упражнения
	DeleteExerciseLog(ctx context.Context, in *DeleteExerciseLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Добавить оценку усилий при выполнении упражнения
	AddPowerRatingToExerciseLog(ctx context.Context, in *AddPowerRatingToExerciseLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Добавление заметки к выполнению упражнения
	AddNotesToExerciseLog(ctx context.Context, in *AddNotesToExerciseLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для создания записи о выполнении подхода
	LogSet(ctx context.Context, in *LogSetRequest, opts ...grpc.CallOption) (*SetLogResponse, error)
	// Метод для изменения записи о выполнении подхода
	UpdateSetLog(ctx context.Context, in *UpdateSetLogRequest, opts ...grpc.CallOption) (*SetLogResponse, error)
	// Удалить запись о выполнении подхода
	DeleteSetLog(ctx context.Context, in *DeleteSetLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для завершения тренировки
	CompleteWorkout(ctx context.Context, in *CompleteWorkoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для получения отчета о тренировке
	GetWorkoutReport(ctx context.Context, in *GetWorkoutReportRequest, opts ...grpc.CallOption) (*WorkoutReportResponse, error)
	// Метод для установки оценки тренировки
	RateWorkout(ctx context.Context, in *RateWorkoutRequest, opts ...grpc.CallOption) (*WorkoutResponse, error)
	// Метод для добавления комментария к тренировке
	AddCommentToWorkout(ctx context.Context, in *AddCommentToWorkoutRequest, opts ...grpc.CallOption) (*WorkoutResponse, error)
	// Изменить единицу измерения веса для ExerciseLog
	UpdateExerciseLogWeightUnit(ctx context.Context, in *UpdateExerciseLogWeightUnitRequest, opts ...grpc.CallOption) (*ExerciseLogResponse, error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) StartWorkout(ctx context.Context, in *StartWorkoutRequest, opts ...grpc.CallOption) (*WorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_StartWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GenerateWorkout(ctx context.Context, in *GenerateWorkoutRequest, opts ...grpc.CallOption) (*GenerateWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GenerateWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkout(ctx context.Context, in *GetWorkoutRequest, opts ...grpc.CallOption) (*GetWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) DeleteWorkout(ctx context.Context, in *DeleteWorkoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_DeleteWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetActiveWorkouts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkoutsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutsListResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetActiveWorkouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkouts(ctx context.Context, in *GetWorkoutsRequest, opts ...grpc.CallOption) (*GetWorkoutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutsResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) LogExercise(ctx context.Context, in *LogExerciseRequest, opts ...grpc.CallOption) (*ExerciseLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseLog)
	err := c.cc.Invoke(ctx, WorkoutService_LogExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetExerciseLogDetails(ctx context.Context, in *GetExerciseLogDetailRequest, opts ...grpc.CallOption) (*ExerciseLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseLogResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetExerciseLogDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) DeleteExerciseLog(ctx context.Context, in *DeleteExerciseLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_DeleteExerciseLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) AddPowerRatingToExerciseLog(ctx context.Context, in *AddPowerRatingToExerciseLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_AddPowerRatingToExerciseLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) AddNotesToExerciseLog(ctx context.Context, in *AddNotesToExerciseLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_AddNotesToExerciseLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) LogSet(ctx context.Context, in *LogSetRequest, opts ...grpc.CallOption) (*SetLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLogResponse)
	err := c.cc.Invoke(ctx, WorkoutService_LogSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) UpdateSetLog(ctx context.Context, in *UpdateSetLogRequest, opts ...grpc.CallOption) (*SetLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLogResponse)
	err := c.cc.Invoke(ctx, WorkoutService_UpdateSetLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) DeleteSetLog(ctx context.Context, in *DeleteSetLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_DeleteSetLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) CompleteWorkout(ctx context.Context, in *CompleteWorkoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_CompleteWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkoutReport(ctx context.Context, in *GetWorkoutReportRequest, opts ...grpc.CallOption) (*WorkoutReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutReportResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkoutReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) RateWorkout(ctx context.Context, in *RateWorkoutRequest, opts ...grpc.CallOption) (*WorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_RateWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) AddCommentToWorkout(ctx context.Context, in *AddCommentToWorkoutRequest, opts ...grpc.CallOption) (*WorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_AddCommentToWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) UpdateExerciseLogWeightUnit(ctx context.Context, in *UpdateExerciseLogWeightUnitRequest, opts ...grpc.CallOption) (*ExerciseLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExerciseLogResponse)
	err := c.cc.Invoke(ctx, WorkoutService_UpdateExerciseLogWeightUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	// Метод для начала новой тренировки
	StartWorkout(context.Context, *StartWorkoutRequest) (*WorkoutResponse, error)
	// Запустить (или перезапустить после ошибки) генерацию тренировки
	GenerateWorkout(context.Context, *GenerateWorkoutRequest) (*GenerateWorkoutResponse, error)
	// Метод для получения состояния тренировки
	GetWorkout(context.Context, *GetWorkoutRequest) (*GetWorkoutResponse, error)
	// Удалить тренировку
	DeleteWorkout(context.Context, *DeleteWorkoutRequest) (*emptypb.Empty, error)
	// Метод для получения списка активных тренировок
	GetActiveWorkouts(context.Context, *emptypb.Empty) (*WorkoutsListResponse, error)
	// Метод для получения списка всех тренировок
	GetWorkouts(context.Context, *GetWorkoutsRequest) (*GetWorkoutsResponse, error)
	// Метод для создания записи о выполнении упражнения
	LogExercise(context.Context, *LogExerciseRequest) (*ExerciseLog, error)
	// Метод для получения записи о выполнении упражнения
	GetExerciseLogDetails(context.Context, *GetExerciseLogDetailRequest) (*ExerciseLogResponse, error)
	// Удалить запись о выполнении упражнения
	DeleteExerciseLog(context.Context, *DeleteExerciseLogRequest) (*emptypb.Empty, error)
	// Добавить оценку усилий при выполнении упражнения
	AddPowerRatingToExerciseLog(context.Context, *AddPowerRatingToExerciseLogRequest) (*emptypb.Empty, error)
	// Добавление заметки к выполнению упражнения
	AddNotesToExerciseLog(context.Context, *AddNotesToExerciseLogRequest) (*emptypb.Empty, error)
	// Метод для создания записи о выполнении подхода
	LogSet(context.Context, *LogSetRequest) (*SetLogResponse, error)
	// Метод для изменения записи о выполнении подхода
	UpdateSetLog(context.Context, *UpdateSetLogRequest) (*SetLogResponse, error)
	// Удалить запись о выполнении подхода
	DeleteSetLog(context.Context, *DeleteSetLogRequest) (*emptypb.Empty, error)
	// Метод для завершения тренировки
	CompleteWorkout(context.Context, *CompleteWorkoutRequest) (*emptypb.Empty, error)
	// Метод для получения отчета о тренировке
	GetWorkoutReport(context.Context, *GetWorkoutReportRequest) (*WorkoutReportResponse, error)
	// Метод для установки оценки тренировки
	RateWorkout(context.Context, *RateWorkoutRequest) (*WorkoutResponse, error)
	// Метод для добавления комментария к тренировке
	AddCommentToWorkout(context.Context, *AddCommentToWorkoutRequest) (*WorkoutResponse, error)
	// Изменить единицу измерения веса для ExerciseLog
	UpdateExerciseLogWeightUnit(context.Context, *UpdateExerciseLogWeightUnitRequest) (*ExerciseLogResponse, error)
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) StartWorkout(context.Context, *StartWorkoutRequest) (*WorkoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GenerateWorkout(context.Context, *GenerateWorkoutRequest) (*GenerateWorkoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkout(context.Context, *GetWorkoutRequest) (*GetWorkoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) DeleteWorkout(context.Context, *DeleteWorkoutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GetActiveWorkouts(context.Context, *emptypb.Empty) (*WorkoutsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveWorkouts not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkouts(context.Context, *GetWorkoutsRequest) (*GetWorkoutsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkouts not implemented")
}
func (UnimplementedWorkoutServiceServer) LogExercise(context.Context, *LogExerciseRequest) (*ExerciseLog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogExercise not implemented")
}
func (UnimplementedWorkoutServiceServer) GetExerciseLogDetails(context.Context, *GetExerciseLogDetailRequest) (*ExerciseLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseLogDetails not implemented")
}
func (UnimplementedWorkoutServiceServer) DeleteExerciseLog(context.Context, *DeleteExerciseLogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExerciseLog not implemented")
}
func (UnimplementedWorkoutServiceServer) AddPowerRatingToExerciseLog(context.Context, *AddPowerRatingToExerciseLogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPowerRatingToExerciseLog not implemented")
}
func (UnimplementedWorkoutServiceServer) AddNotesToExerciseLog(context.Context, *AddNotesToExerciseLogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNotesToExerciseLog not implemented")
}
func (UnimplementedWorkoutServiceServer) LogSet(context.Context, *LogSetRequest) (*SetLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogSet not implemented")
}
func (UnimplementedWorkoutServiceServer) UpdateSetLog(context.Context, *UpdateSetLogRequest) (*SetLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSetLog not implemented")
}
func (UnimplementedWorkoutServiceServer) DeleteSetLog(context.Context, *DeleteSetLogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSetLog not implemented")
}
func (UnimplementedWorkoutServiceServer) CompleteWorkout(context.Context, *CompleteWorkoutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkoutReport(context.Context, *GetWorkoutReportRequest) (*WorkoutReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkoutReport not implemented")
}
func (UnimplementedWorkoutServiceServer) RateWorkout(context.Context, *RateWorkoutRequest) (*WorkoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) AddCommentToWorkout(context.Context, *AddCommentToWorkoutRequest) (*WorkoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommentToWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) UpdateExerciseLogWeightUnit(context.Context, *UpdateExerciseLogWeightUnitRequest) (*ExerciseLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExerciseLogWeightUnit not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_StartWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).StartWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_StartWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).StartWorkout(ctx, req.(*StartWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GenerateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GenerateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GenerateWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GenerateWorkout(ctx, req.(*GenerateWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkout(ctx, req.(*GetWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_DeleteWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).DeleteWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_DeleteWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).DeleteWorkout(ctx, req.(*DeleteWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetActiveWorkouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetActiveWorkouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetActiveWorkouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetActiveWorkouts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkouts(ctx, req.(*GetWorkoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_LogExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).LogExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_LogExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).LogExercise(ctx, req.(*LogExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetExerciseLogDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseLogDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetExerciseLogDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetExerciseLogDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetExerciseLogDetails(ctx, req.(*GetExerciseLogDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_DeleteExerciseLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExerciseLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).DeleteExerciseLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_DeleteExerciseLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).DeleteExerciseLog(ctx, req.(*DeleteExerciseLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_AddPowerRatingToExerciseLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPowerRatingToExerciseLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).AddPowerRatingToExerciseLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_AddPowerRatingToExerciseLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).AddPowerRatingToExerciseLog(ctx, req.(*AddPowerRatingToExerciseLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_AddNotesToExerciseLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNotesToExerciseLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).AddNotesToExerciseLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_AddNotesToExerciseLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).AddNotesToExerciseLog(ctx, req.(*AddNotesToExerciseLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_LogSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).LogSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_LogSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).LogSet(ctx, req.(*LogSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_UpdateSetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).UpdateSetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_UpdateSetLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).UpdateSetLog(ctx, req.(*UpdateSetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_DeleteSetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).DeleteSetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_DeleteSetLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).DeleteSetLog(ctx, req.(*DeleteSetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_CompleteWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).CompleteWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_CompleteWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).CompleteWorkout(ctx, req.(*CompleteWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkoutReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkoutReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkoutReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkoutReport(ctx, req.(*GetWorkoutReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_RateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).RateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_RateWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).RateWorkout(ctx, req.(*RateWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_AddCommentToWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentToWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).AddCommentToWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_AddCommentToWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).AddCommentToWorkout(ctx, req.(*AddCommentToWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_UpdateExerciseLogWeightUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExerciseLogWeightUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).UpdateExerciseLogWeightUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_UpdateExerciseLogWeightUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).UpdateExerciseLogWeightUnit(ctx, req.(*UpdateExerciseLogWeightUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitness_trainer.api.workout.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWorkout",
			Handler:    _WorkoutService_StartWorkout_Handler,
		},
		{
			MethodName: "GenerateWorkout",
			Handler:    _WorkoutService_GenerateWorkout_Handler,
		},
		{
			MethodName: "GetWorkout",
			Handler:    _WorkoutService_GetWorkout_Handler,
		},
		{
			MethodName: "DeleteWorkout",
			Handler:    _WorkoutService_DeleteWorkout_Handler,
		},
		{
			MethodName: "GetActiveWorkouts",
			Handler:    _WorkoutService_GetActiveWorkouts_Handler,
		},
		{
			MethodName: "GetWorkouts",
			Handler:    _WorkoutService_GetWorkouts_Handler,
		},
		{
			MethodName: "LogExercise",
			Handler:    _WorkoutService_LogExercise_Handler,
		},
		{
			MethodName: "GetExerciseLogDetails",
			Handler:    _WorkoutService_GetExerciseLogDetails_Handler,
		},
		{
			MethodName: "DeleteExerciseLog",
			Handler:    _WorkoutService_DeleteExerciseLog_Handler,
		},
		{
			MethodName: "AddPowerRatingToExerciseLog",
			Handler:    _WorkoutService_AddPowerRatingToExerciseLog_Handler,
		},
		{
			MethodName: "AddNotesToExerciseLog",
			Handler:    _WorkoutService_AddNotesToExerciseLog_Handler,
		},
		{
			MethodName: "LogSet",
			Handler:    _WorkoutService_LogSet_Handler,
		},
		{
			MethodName: "UpdateSetLog",
			Handler:    _WorkoutService_UpdateSetLog_Handler,
		},
		{
			MethodName: "DeleteSetLog",
			Handler:    _WorkoutService_DeleteSetLog_Handler,
		},
		{
			MethodName: "CompleteWorkout",
			Handler:    _WorkoutService_CompleteWorkout_Handler,
		},
		{
			MethodName: "GetWorkoutReport",
			Handler:    _WorkoutService_GetWorkoutReport_Handler,
		},
		{
			MethodName: "RateWorkout",
			Handler:    _WorkoutService_RateWorkout_Handler,
		},
		{
			MethodName: "AddCommentToWorkout",
			Handler:    _WorkoutService_AddCommentToWorkout_Handler,
		},
		{
			MethodName: "UpdateExerciseLogWeightUnit",
			Handler:    _WorkoutService_UpdateExerciseLogWeightUnit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workouts/workouts.proto",
}

const (
	UserService_GetUser_FullMethodName                         = "/fitness_trainer.api.workout.UserService/GetUser"
	UserService_GetMe_FullMethodName                           = "/fitness_trainer.api.workout.UserService/GetMe"
	UserService_UpdateUser_FullMethodName                      = "/fitness_trainer.api.workout.UserService/UpdateUser"
	UserService_UpdateWorkoutGenerationSettings_FullMethodName = "/fitness_trainer.api.workout.UserService/UpdateWorkoutGenerationSettings"
	UserService_GetWorkoutGenerationSettings_FullMethodName    = "/fitness_trainer.api.workout.UserService/GetWorkoutGenerationSettings"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// Метод для получения пользователя по ID
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Метод для получения текущего пользователя
	GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserResponse, error)
	// Метод для обновления данных пользователя
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Метод для обновления настроек генерации тренировок
	UpdateWorkoutGenerationSettings(ctx context.Context, in *UpdateWorkoutGenerationSettingsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод для получения настроек генерации тренировок
	GetWorkoutGenerationSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkoutGenerationSettingsResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateWorkoutGenerationSettings(ctx context.Context, in *UpdateWorkoutGenerationSettingsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_UpdateWorkoutGenerationSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetWorkoutGenerationSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkoutGenerationSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutGenerationSettingsResponse)
	err := c.cc.Invoke(ctx, UserService_GetWorkoutGenerationSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	// Метод для получения пользователя по ID
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	// Метод для получения текущего пользователя
	GetMe(context.Context, *emptypb.Empty) (*UserResponse, error)
	// Метод для обновления данных пользователя
	UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error)
	// Метод для обновления настроек генерации тренировок
	UpdateWorkoutGenerationSettings(context.Context, *UpdateWorkoutGenerationSettingsRequest) (*emptypb.Empty, error)
	// Метод для получения настроек генерации тренировок
	GetWorkoutGenerationSettings(context.Context, *emptypb.Empty) (*WorkoutGenerationSettingsResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) GetMe(context.Context, *emptypb.Empty) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateWorkoutGenerationSettings(context.Context, *UpdateWorkoutGenerationSettingsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkoutGenerationSettings not implemented")
}
func (UnimplementedUserServiceServer) GetWorkoutGenerationSettings(context.Context, *emptypb.Empty) (*WorkoutGenerationSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkoutGenerationSettings not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateWorkoutGenerationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkoutGenerationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateWorkoutGenerationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateWorkoutGenerationSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateWorkoutGenerationSettings(ctx, req.(*UpdateWorkoutGenerationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetWorkoutGenerationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetWorkoutGenerationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetWorkoutGenerationSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetWorkoutGenerationSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitness_trainer.api.workout.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _UserService_GetMe_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateWorkoutGenerationSettings",
			Handler:    _UserService_UpdateWorkoutGenerationSettings_Handler,
		},
		{
			MethodName: "GetWorkoutGenerationSettings",
			Handler:    _UserService_GetWorkoutGenerationSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workouts/workouts.proto",
}

const (
	FileService_PresignUpload_FullMethodName = "/fitness_trainer.api.workout.FileService/PresignUpload"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	PresignUpload(ctx context.Context, in *PresignUploadRequest, opts ...grpc.CallOption) (*PresignUploadResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) PresignUpload(ctx context.Context, in *PresignUploadRequest, opts ...grpc.CallOption) (*PresignUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignUploadResponse)
	err := c.cc.Invoke(ctx, FileService_PresignUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	PresignUpload(context.Context, *PresignUploadRequest) (*PresignUploadResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) PresignUpload(context.Context, *PresignUploadRequest) (*PresignUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignUpload not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_PresignUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).PresignUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_PresignUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).PresignUpload(ctx, req.(*PresignUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitness_trainer.api.workout.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PresignUpload",
			Handler:    _FileService_PresignUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workouts/workouts.proto",
}

const (
	ChatService_SendChatMessageStream_FullMethodName = "/fitness_trainer.api.workout.ChatService/SendChatMessageStream"
	ChatService_GetChat_FullMethodName               = "/fitness_trainer.api.workout.ChatService/GetChat"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	// Отправить сообщение в чат и получить поток ответов
	SendChatMessageStream(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendChatMessageStreamResponse], error)
	// Получить полный чат с сообщениями
	GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SendChatMessageStream(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendChatMessageStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_SendChatMessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendChatMessageRequest, SendChatMessageStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SendChatMessageStreamClient = grpc.ServerStreamingClient[SendChatMessageStreamResponse]

func (c *chatServiceClient) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatResponse)
	err := c.cc.Invoke(ctx, ChatService_GetChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	// Отправить сообщение в чат и получить поток ответов
	SendChatMessageStream(*SendChatMessageRequest, grpc.ServerStreamingServer[SendChatMessageStreamResponse]) error
	// Получить полный чат с сообщениями
	GetChat(context.Context, *GetChatRequest) (*GetChatResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) SendChatMessageStream(*SendChatMessageRequest, grpc.ServerStreamingServer[SendChatMessageStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendChatMessageStream not implemented")
}
func (UnimplementedChatServiceServer) GetChat(context.Context, *GetChatRequest) (*GetChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_SendChatMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendChatMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).SendChatMessageStream(m, &grpc.GenericServerStream[SendChatMessageRequest, SendChatMessageStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SendChatMessageStreamServer = grpc.ServerStreamingServer[SendChatMessageStreamResponse]

func _ChatService_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetChat(ctx, req.(*GetChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fitness_trainer.api.workout.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChat",
			Handler:    _ChatService_GetChat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendChatMessageStream",
			Handler:       _ChatService_SendChatMessageStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workouts/workouts.proto",
}
